%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\hauti\heli-fw\MyCasesNew\t100\VBZ_PSI.dat
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2024/07/05 17:39:47
function [timeflightmat, timeflight, t0rfw, t1cfw, t1sfw, b0r, b1c, b1s, timeflight_lastline] = importtimeflight(speed, filepath1, filepath2)

timeflight = zeros(50,9,length(speed));

for i = 1:length(speed)
    %% Initialize variables.
    % filename = ['C:\Users\hauti\heli-fw\MyCasesNew\t' num2str(speed(i)) '\timeflightmodified.dat'];
    filename = [filepath1 num2str(speed(i)) filepath2 '\timeflightmodified.dat'];

    %% Format for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    %   column9: double (%f)
    % For more information, see the TEXTSCAN documentation.
    % formatSpec = '%12f%26f%26f%21f%31f%26f%26f%21f%26f%[^\n\r]';
    formatSpec = '%12f%26f%26f%21f%31f%26f%26f%26f%26f%[^\n\r]';
    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string',  'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.
    
    % Constructing the output matrix of the timeflightmodified.dat file
    timeflight = [dataArray{1:end-1}];
    len = length(timeflight(:,1));
    timeflightmat(1:length(timeflight(:,1,:)),1:length(timeflight(1,:,:)),i) = timeflight;
    timeflight_lastline = timeflightmat(len,4:9,i);
    % Constructing the vector of tail rotor collective pitch angle at the
    % different flight speeds.
    t0rfw(i) = rad2deg(timeflightmat(len,4,i));
    t1cfw(i) = rad2deg(timeflightmat(len,5,i));
    t1sfw(i) = rad2deg(timeflightmat(len,6,i));
    b0r(i) = rad2deg(timeflightmat(len,7,i));
    b1c(i) = rad2deg(timeflightmat(len,8,i));
    b1s(i) = rad2deg(timeflightmat(len,9,i));
    % disp(b1s)

    %% Clear temporary variables
    clearvars filename formatSpec fileID dataArray ans;
end