function trimdata = importTRIMDATA(speed)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\hauti\heliumx2\HeliUM.sample\uh60a_fw_1kt\TRIMPLOTDATA.DAT
%
% Auto-generated by MATLAB on 10-Jul-2024 16:53:06
for i = 1:length(speed)
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 2);

    % Specify range and delimiter
    opts.DataLines = [1, Inf];
    opts.Delimiter = " ";

    % Specify column names and types
    opts.VariableNames = ["VarName1", "Var2"];
    opts.SelectedVariableNames = "VarName1";
    opts.VariableTypes = ["double", "string"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.ConsecutiveDelimitersRule = "join";
    opts.LeadingDelimitersRule = "ignore";

    % Specify variable properties
    opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "VarName1", "TrimNonNumeric", true);
    opts = setvaropts(opts, "VarName1", "ThousandsSeparator", ",");

    % Import the data
    filename = ['C:\Users\hauti\heliumx2\HeliUM.sample\uh60a_fw_' num2str(speed(i)) 'kt\TRIMPLOTDATA.DAT'];
    trim = readtable(filename, opts);
    trimdata(i,:) = table2array(trim);
    %% Clear temporary variables
    clear opts

end